### ISSUE TITLE
Investigate eks fargate proxy

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#229]
we seem to have issues when running on fargate and trying to proxy.  we see certain errors about connection timeouts but im not sure why the ips are incorrect yet. https://github.com/klothoplatform/klotho/issues/201 would likely solve this issue but we should see if theres something wrong in one of the controllers

```
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT 10.0.136.210:5432
    at Client._connectionCallback (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)
    at Client._handleErrorWhileConnecting (/usr/src/app/node_modules/pg/lib/client.js:316:19)
    at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:326:19)
    at Connection.emit (node:events:512:28)
    at Socket.reportStreamError (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  parent: Error: connect ETIMEDOUT 10.0.136.210:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '10.0.136.210',
    port: 5432
  },
  original: Error: connect ETIMEDOUT 10.0.136.210:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '10.0.136.210',
    port: 5432
  }
}
```

**Comment by jhsinger-klotho** [comment]
So we can prove this is purely due to the SQL issue we are seeing in the error above and nothing to do with proxying itself. Going to resolve this since we have an open ticket for the upgrade issues
