### ISSUE TITLE
eks upgrade failures

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#230]
saw this error when debugging

```
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT 10.0.200.114:5432
    at Client._connectionCallback (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)
    at Client._handleErrorWhileConnecting (/usr/src/app/node_modules/pg/lib/client.js:316:19)
    at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:326:19)
    at Connection.emit (node:events:512:28)
    at Socket.reportStreamError (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  parent: Error: connect ETIMEDOUT 10.0.200.114:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '10.0.200.114',
    port: 5432
  },
  original: Error: connect ETIMEDOUT 10.0.200.114:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '10.0.200.114',
    port: 5432
  }
}

```

**Comment by jhsinger-klotho** [comment]
```
 -   ├─ aws:ec2:SecurityGroupRule                                                     farg-prox-private-ingress                                                                         deleted (0.75s)
 -   ├─ aws:ec2:SecurityGroupRule                                                     farg-prox-public-ingress                                                                          deleted (0.59s)
 - ```

amihan also pointed out that these rules were getting removed for some reason. When you run pulumi refresh you see them deleted and then recreated when you run up again. Not sure why

**Comment by jhsinger-klotho** [comment]
when you re run pulumi up those are recreated and then tests pass
