### ISSUE TITLE
Unable to create topic ts-app ecs-executor

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#361]
when running the sample ap we fail to compile the 002-ecs-executor config. Looks like its due to pubsub

```
    error: Running program '/Users/jordansinger/workspace/infra-tests/apps/ts-app/compiled/' failed with an unhandled exception:
    TypeError: Cannot read properties of undefined (reading 'arn')
        at CloudCCLib.createTopic [90m(/Users/jordansinger/workspace/infra-tests/apps/ts-app/compiled/[39mdeploylib.ts:700:36[90m)[39m
        at module.exports [90m(/Users/jordansinger/workspace/infra-tests/apps/ts-app/compiled/[39mindex.ts:594:14[90m)[39m
```

**Comment by jhsinger-klotho** [comment]
this is due to pubbsub not working with ecs and eks. We should still create the resource, but runtime should break

**Comment by gordon-klotho** [comment]
Related: https://github.com/klothoplatform/klotho-history/issues/407

We should probably fail the compilation for unsupported combinations of capabilities and types like this.

**Comment by yuval-klotho** [comment]
* if we don't want to fix pubsub, we should fail within the klotho compilation
* testing implication: we'd need to either rework the app runner so that we don't test ecs/eks with pubsub, or fix this
  * we could also just remove pubsub 🙃 or make it untested within mega-app
  * we already have ts-events in sample-apps-pro, which tests it for lambda

For now:
* will remove this from mega-app
* outstanding work (this ticket) will be to fail compilation
