### ISSUE TITLE
Visualization Translation

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#499]
Convert Resource DAG to our visualization IR

Definition of Done: 

- On every klotho compilation, we are able to output a diagram as a png

**Comment by gordon-klotho** [comment]
Putting this down for now to pivot onto other things.

🚧 WIP 🚧 
https://github.com/klothoplatform/klotho/tree/ifc2/vis_output (output the topology yaml and call visualizer for image)
+
https://github.com/klothoplatform/visualizer/tree/klotho_integration (change some group directions, converting types, other fixes)

Added `topology.yaml` which is the topology as output from the `vis_output` branch for the `go-expose` sample app.
Currently running into this error on the visualizer:
```
Traceback (most recent call last):
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/gordon/.local/share/virtualenvs/visualizer-N6ijiUmh/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/gordon/workspace/visualizer/app/main.py", line 38, in generate_infra_diagram
    filepath = generate_resource_diagram(application)
  File "/home/gordon/workspace/visualizer/app/main.py", line 82, in generate_resource_diagram
    awsgenerator.apply_node(node)
  File "/home/gordon/workspace/visualizer/app/aws/generator.py", line 71, in apply_node
    self.resource_visualizers.get(f"{node.id.resource_type.replace(':', '')}", self.default_node_handler)(node)
  File "/home/gordon/workspace/visualizer/app/decorators.py", line 9, in wrapper
    return func(*args, **kwargs)
TypeError: subnet() missing 1 required positional argument: 'resource'
```

**Comment by gordon-klotho** [comment]
Next Steps:
1. Fix Error above (and any other errors)
2. Fix type conversions (so they don't all just use the default image)
3. Add node properties (just subnet CIDR and public/private might be fine for now)
4. Edge collapsing for API gateway

**Comment by yuval-klotho** [comment]
> 4. Edge collapsing for API gateway

We're going to punt on this for now, in interest of time.
